name: WePY Test Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name : GITHUB CONTEXT
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
  release:
    if: github.event_name == 'push' && startsWith(github.event.head_commit.message, 'release:')
    name: Release
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - run: git reset --hard
    - run: |
        git config --global user.email "gcaufy@gmail.com"
        git config --global user.name "WePY CI"
    - run: npm install
    - run: npm run bootstrap
    - run: git status
    - run: git reset --hard
    - name: Version
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node ./scripts/ci-version.js "${{ github.event.head_commit.message }}"
    - run: npx lerna publish
    - run: git status
    - run: git log
