name: WePY Test Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [8.x, 10.x]
    steps:
    - name : GITHUB CONTEXT
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
  release:
    if: github.event_name == 'push' && startsWith(github.event.head_commit.message, 'release:')
    name: Release
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - run: npm install
    - run: npm run bootstrap
    - run: node ./scripts/ci-version.js "${{ github.event.head_commit.message }}"
    - run: npx lerna publish
    - run: git status
    - run: git log
